import { GraphQLError } from "graphql";

const DEFAULT_PAGE_SIZE = 5;
const MAX_PAGE_SIZE = 20;

export interface PostsArguments {
  first?: number | null;
  after?: string | null;
}

function invalidArgument(message: string): GraphQLError {
  return new GraphQLError(message, {
    extensions: { code: "BAD_USER_INPUT" },
  });
}

// 1. VALIDATE THE REQUESTED PAGE SIZE
export function validatePageSize(first: number | null | undefined): number {
  const pageSize = first === undefined ? DEFAULT_PAGE_SIZE : first;

  if (
    typeof pageSize !== "number" ||
    !Number.isInteger(pageSize) ||
    pageSize < 1 ||
    pageSize > MAX_PAGE_SIZE
  ) {
    throw invalidArgument(
      `first must be an integer between 1 and ${MAX_PAGE_SIZE}`,
    );
  }

  return pageSize;
}

// 2. ENCODE THE POSITION OF A POST
export function encodePostCursor(id: string): string {
  return Buffer.from(JSON.stringify({ version: 1, id }), "utf8").toString(
    "base64url",
  );
}

// 3. DECODE AND VALIDATE A CLIENT-SUPPLIED CURSOR
export function decodePostCursor(cursor: string): string {
  if (
    cursor.length === 0 ||
    cursor.length > 1024 ||
    !/^[A-Za-z0-9_-]+$/.test(cursor)
  ) {
    throw invalidArgument("Invalid posts cursor");
  }

  try {
    const value: unknown = JSON.parse(
      Buffer.from(cursor, "base64url").toString("utf8"),
    );

    if (
      typeof value !== "object" ||
      value === null ||
      !("version" in value) ||
      value.version !== 1 ||
      !("id" in value) ||
      typeof value.id !== "string" ||
      value.id.length === 0 ||
      value.id.length > 256
    ) {
      throw new Error("Invalid cursor payload");
    }

    // Accept only the exact format generated by our encoder.
    if (encodePostCursor(value.id) !== cursor) {
      throw new Error("Noncanonical cursor");
    }

    return value.id;
  } catch {
    throw invalidArgument("Invalid posts cursor");
  }
}

// 4. VALIDATE ARGUMENTS BEFORE QUERYING MONGODB
export function parsePostsArguments(args: PostsArguments): {
  pageSize: number;
  afterId: string | null;
} {
  const pageSize = validatePageSize(args.first);

  const afterId =
    args.after === undefined || args.after === null
      ? null
      : decodePostCursor(args.after);

  return { pageSize, afterId };
}
